//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
